// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ProviderServiceType.
const (
	ProviderServiceTypeContainer ProviderServiceType = "container"
	ProviderServiceTypeDatabase  ProviderServiceType = "database"
	ProviderServiceTypePod       ProviderServiceType = "pod"
	ProviderServiceTypeStorage   ProviderServiceType = "storage"
	ProviderServiceTypeVm        ProviderServiceType = "vm"
)

// Defines values for ProviderRegistrationServiceType.
const (
	ProviderRegistrationServiceTypeContainer ProviderRegistrationServiceType = "container"
	ProviderRegistrationServiceTypeDatabase  ProviderRegistrationServiceType = "database"
	ProviderRegistrationServiceTypePod       ProviderRegistrationServiceType = "pod"
	ProviderRegistrationServiceTypeStorage   ProviderRegistrationServiceType = "storage"
	ProviderRegistrationServiceTypeVm        ProviderRegistrationServiceType = "vm"
)

// Defines values for ProviderResponseStatus.
const (
	Registered ProviderResponseStatus = "registered"
	Updated    ProviderResponseStatus = "updated"
)

// Error RFC 7807 compliant error response
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference for this specific error occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int `json:"status,omitempty"`

	// Title Short human-readable summary of the problem
	Title string `json:"title"`

	// Type URI reference identifying the error type
	Type string `json:"type"`
}

// Provider Full provider resource representation
type Provider struct {
	// CreateTime Timestamp when the provider was first registered
	CreateTime *time.Time `json:"create_time,omitempty"`

	// DisplayName Human-readable display name for the provider
	DisplayName *string `json:"display_name,omitempty"`

	// Endpoint Full endpoint URL where the provider API is accessible
	Endpoint string `json:"endpoint"`

	// Id Unique identifier for the Service Provider
	Id openapi_types.UUID `json:"id"`

	// Metadata Additional metadata about the provider
	Metadata *ProviderMetadata `json:"metadata,omitempty"`

	// Name Unique name of the Service Provider
	Name string `json:"name"`

	// Operations List of operations supported for this service type
	Operations *[]string `json:"operations,omitempty"`

	// Path Resource path identifier
	Path *string `json:"path,omitempty"`

	// ServiceType Type of service this provider offers
	ServiceType ProviderServiceType `json:"service_type"`

	// UpdateTime Timestamp when the provider was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// ProviderServiceType Type of service this provider offers
type ProviderServiceType string

// ProviderList Paginated list of providers
type ProviderList struct {
	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string     `json:"next_page_token,omitempty"`
	Providers     *[]Provider `json:"providers,omitempty"`
}

// ProviderMetadata Additional metadata about the provider
type ProviderMetadata struct {
	// RegionCode Geographic region code where the provider operates
	RegionCode *string `json:"region_code,omitempty"`

	// Resources Resource capacity information
	Resources *ResourceCapacity `json:"resources,omitempty"`

	// Status Current operational status of the provider
	Status *string `json:"status,omitempty"`

	// Zone Availability zone or datacenter identifier
	Zone *string `json:"zone,omitempty"`
}

// ProviderRegistration Registration payload for a service provider
type ProviderRegistration struct {
	// DisplayName Human-readable display name for the provider
	DisplayName *string `json:"display_name,omitempty"`

	// Endpoint Full endpoint URL where the provider API is accessible
	Endpoint string `json:"endpoint"`

	// Id Optional unique identifier for the Service Provider.
	// If not provided, DCM will generate one automatically.
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Metadata Additional metadata about the provider
	Metadata *ProviderMetadata `json:"metadata,omitempty"`

	// Name Unique name of the Service Provider.
	// Used as the natural key for matching existing registrations.
	Name string `json:"name"`

	// Operations List of operations supported for this service type
	Operations *[]string `json:"operations,omitempty"`

	// Path Resource path identifier
	Path *string `json:"path,omitempty"`

	// ServiceType Type of service this provider offers.
	// Each provider registration is per service type.
	ServiceType ProviderRegistrationServiceType `json:"service_type"`
}

// ProviderRegistrationServiceType Type of service this provider offers.
// Each provider registration is per service type.
type ProviderRegistrationServiceType string

// ProviderResponse Response payload after provider registration
type ProviderResponse struct {
	// Id Unique identifier for the Service Provider
	Id openapi_types.UUID `json:"id"`

	// Path Resource path identifier
	Path *string `json:"path,omitempty"`

	// Provider Full provider resource representation
	Provider *Provider `json:"provider,omitempty"`

	// Status Registration status
	Status ProviderResponseStatus `json:"status"`
}

// ProviderResponseStatus Registration status
type ProviderResponseStatus string

// ResourceCapacity Resource capacity information
type ResourceCapacity struct {
	// TotalCpu Total CPU cores available
	TotalCpu *int `json:"total_cpu,omitempty"`

	// TotalMemory Total memory available
	TotalMemory *string `json:"total_memory,omitempty"`

	// TotalNode Total number of nodes
	TotalNode *int `json:"total_node,omitempty"`

	// TotalStorage Total storage available
	TotalStorage *string `json:"total_storage,omitempty"`
}

// ListProvidersParams defines parameters for ListProviders.
type ListProvidersParams struct {
	// Type Filter providers by service type
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// MaxPageSize Maximum number of results per page
	MaxPageSize *int `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// PageToken Token for pagination
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateProviderParams defines parameters for CreateProvider.
type CreateProviderParams struct {
	// Id Optional provider ID for idempotent registration
	Id *openapi_types.UUID `form:"id,omitempty" json:"id,omitempty"`
}

// CreateProviderJSONRequestBody defines body for CreateProvider for application/json ContentType.
type CreateProviderJSONRequestBody = ProviderRegistration

// ApplyProviderJSONRequestBody defines body for ApplyProvider for application/json ContentType.
type ApplyProviderJSONRequestBody = Provider

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	Health(w http.ResponseWriter, r *http.Request)
	// List all providers
	// (GET /providers)
	ListProviders(w http.ResponseWriter, r *http.Request, params ListProvidersParams)
	// Register a Service Provider
	// (POST /providers)
	CreateProvider(w http.ResponseWriter, r *http.Request, params CreateProviderParams)
	// Delete a service Provider
	// (DELETE /providers/{providerId})
	DeleteProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID)
	// Get a provider
	// (GET /providers/{providerId})
	GetProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID)
	// Update a Service Provider
	// (PUT /providers/{providerId})
	ApplyProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Health check
// (GET /health)
func (_ Unimplemented) Health(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all providers
// (GET /providers)
func (_ Unimplemented) ListProviders(w http.ResponseWriter, r *http.Request, params ListProvidersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a Service Provider
// (POST /providers)
func (_ Unimplemented) CreateProvider(w http.ResponseWriter, r *http.Request, params CreateProviderParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a service Provider
// (DELETE /providers/{providerId})
func (_ Unimplemented) DeleteProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a provider
// (GET /providers/{providerId})
func (_ Unimplemented) GetProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a Service Provider
// (PUT /providers/{providerId})
func (_ Unimplemented) ApplyProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProviders operation middleware
func (siw *ServerInterfaceWrapper) ListProviders(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProvidersParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "max_page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "max_page_size", r.URL.Query(), &params.MaxPageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProviders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProvider operation middleware
func (siw *ServerInterfaceWrapper) CreateProvider(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateProviderParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProvider(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProvider operation middleware
func (siw *ServerInterfaceWrapper) DeleteProvider(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "providerId" -------------
	var providerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "providerId", chi.URLParam(r, "providerId"), &providerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProvider(w, r, providerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProvider operation middleware
func (siw *ServerInterfaceWrapper) GetProvider(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "providerId" -------------
	var providerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "providerId", chi.URLParam(r, "providerId"), &providerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProvider(w, r, providerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApplyProvider operation middleware
func (siw *ServerInterfaceWrapper) ApplyProvider(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "providerId" -------------
	var providerId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "providerId", chi.URLParam(r, "providerId"), &providerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyProvider(w, r, providerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.Health)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/providers", wrapper.ListProviders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/providers", wrapper.CreateProvider)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/providers/{providerId}", wrapper.DeleteProvider)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/providers/{providerId}", wrapper.GetProvider)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/providers/{providerId}", wrapper.ApplyProvider)
	})

	return r
}

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(w http.ResponseWriter) error
}

type Health200JSONResponse struct {
	Status *string `json:"status,omitempty"`
}

func (response Health200JSONResponse) VisitHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListProvidersRequestObject struct {
	Params ListProvidersParams
}

type ListProvidersResponseObject interface {
	VisitListProvidersResponse(w http.ResponseWriter) error
}

type ListProviders200JSONResponse ProviderList

func (response ListProviders200JSONResponse) VisitListProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListProviders400ApplicationProblemPlusJSONResponse Error

func (response ListProviders400ApplicationProblemPlusJSONResponse) VisitListProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListProvidersdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListProvidersdefaultApplicationProblemPlusJSONResponse) VisitListProvidersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateProviderRequestObject struct {
	Params CreateProviderParams
	Body   *CreateProviderJSONRequestBody
}

type CreateProviderResponseObject interface {
	VisitCreateProviderResponse(w http.ResponseWriter) error
}

type CreateProvider200JSONResponse ProviderResponse

func (response CreateProvider200JSONResponse) VisitCreateProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateProvider201JSONResponse ProviderResponse

func (response CreateProvider201JSONResponse) VisitCreateProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateProvider400ApplicationProblemPlusJSONResponse Error

func (response CreateProvider400ApplicationProblemPlusJSONResponse) VisitCreateProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateProvider409ApplicationProblemPlusJSONResponse Error

func (response CreateProvider409ApplicationProblemPlusJSONResponse) VisitCreateProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateProvider422ApplicationProblemPlusJSONResponse Error

func (response CreateProvider422ApplicationProblemPlusJSONResponse) VisitCreateProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateProviderdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateProviderdefaultApplicationProblemPlusJSONResponse) VisitCreateProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteProviderRequestObject struct {
	ProviderId openapi_types.UUID `json:"providerId"`
}

type DeleteProviderResponseObject interface {
	VisitDeleteProviderResponse(w http.ResponseWriter) error
}

type DeleteProvider204Response struct {
}

func (response DeleteProvider204Response) VisitDeleteProviderResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteProvider400ApplicationProblemPlusJSONResponse Error

func (response DeleteProvider400ApplicationProblemPlusJSONResponse) VisitDeleteProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProvider404ApplicationProblemPlusJSONResponse Error

func (response DeleteProvider404ApplicationProblemPlusJSONResponse) VisitDeleteProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProviderdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteProviderdefaultApplicationProblemPlusJSONResponse) VisitDeleteProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetProviderRequestObject struct {
	ProviderId openapi_types.UUID `json:"providerId"`
}

type GetProviderResponseObject interface {
	VisitGetProviderResponse(w http.ResponseWriter) error
}

type GetProvider200JSONResponse Provider

func (response GetProvider200JSONResponse) VisitGetProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProvider400ApplicationProblemPlusJSONResponse Error

func (response GetProvider400ApplicationProblemPlusJSONResponse) VisitGetProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetProvider404ApplicationProblemPlusJSONResponse Error

func (response GetProvider404ApplicationProblemPlusJSONResponse) VisitGetProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetProviderdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetProviderdefaultApplicationProblemPlusJSONResponse) VisitGetProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ApplyProviderRequestObject struct {
	ProviderId openapi_types.UUID `json:"providerId"`
	Body       *ApplyProviderJSONRequestBody
}

type ApplyProviderResponseObject interface {
	VisitApplyProviderResponse(w http.ResponseWriter) error
}

type ApplyProvider200JSONResponse Provider

func (response ApplyProvider200JSONResponse) VisitApplyProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ApplyProvider400ApplicationProblemPlusJSONResponse Error

func (response ApplyProvider400ApplicationProblemPlusJSONResponse) VisitApplyProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ApplyProvider404ApplicationProblemPlusJSONResponse Error

func (response ApplyProvider404ApplicationProblemPlusJSONResponse) VisitApplyProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ApplyProvider409ApplicationProblemPlusJSONResponse Error

func (response ApplyProvider409ApplicationProblemPlusJSONResponse) VisitApplyProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ApplyProviderdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ApplyProviderdefaultApplicationProblemPlusJSONResponse) VisitApplyProviderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Health check
	// (GET /health)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)
	// List all providers
	// (GET /providers)
	ListProviders(ctx context.Context, request ListProvidersRequestObject) (ListProvidersResponseObject, error)
	// Register a Service Provider
	// (POST /providers)
	CreateProvider(ctx context.Context, request CreateProviderRequestObject) (CreateProviderResponseObject, error)
	// Delete a service Provider
	// (DELETE /providers/{providerId})
	DeleteProvider(ctx context.Context, request DeleteProviderRequestObject) (DeleteProviderResponseObject, error)
	// Get a provider
	// (GET /providers/{providerId})
	GetProvider(ctx context.Context, request GetProviderRequestObject) (GetProviderResponseObject, error)
	// Update a Service Provider
	// (PUT /providers/{providerId})
	ApplyProvider(ctx context.Context, request ApplyProviderRequestObject) (ApplyProviderResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Health operation middleware
func (sh *strictHandler) Health(w http.ResponseWriter, r *http.Request) {
	var request HealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx, request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		if err := validResponse.VisitHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProviders operation middleware
func (sh *strictHandler) ListProviders(w http.ResponseWriter, r *http.Request, params ListProvidersParams) {
	var request ListProvidersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProviders(ctx, request.(ListProvidersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProviders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProvidersResponseObject); ok {
		if err := validResponse.VisitListProvidersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProvider operation middleware
func (sh *strictHandler) CreateProvider(w http.ResponseWriter, r *http.Request, params CreateProviderParams) {
	var request CreateProviderRequestObject

	request.Params = params

	var body CreateProviderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProvider(ctx, request.(CreateProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProvider")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateProviderResponseObject); ok {
		if err := validResponse.VisitCreateProviderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteProvider operation middleware
func (sh *strictHandler) DeleteProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	var request DeleteProviderRequestObject

	request.ProviderId = providerId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProvider(ctx, request.(DeleteProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProvider")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteProviderResponseObject); ok {
		if err := validResponse.VisitDeleteProviderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProvider operation middleware
func (sh *strictHandler) GetProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	var request GetProviderRequestObject

	request.ProviderId = providerId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProvider(ctx, request.(GetProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProvider")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProviderResponseObject); ok {
		if err := validResponse.VisitGetProviderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApplyProvider operation middleware
func (sh *strictHandler) ApplyProvider(w http.ResponseWriter, r *http.Request, providerId openapi_types.UUID) {
	var request ApplyProviderRequestObject

	request.ProviderId = providerId

	var body ApplyProviderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyProvider(ctx, request.(ApplyProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyProvider")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyProviderResponseObject); ok {
		if err := validResponse.VisitApplyProviderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
