// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabVMcNxL+K6q5q0pSt+9s7Hi/YSDOOoZwGJLKGRelnenZkdFIsqRZmLj2v19Jmtcd",
	"LV7nMFBX/jagl261up9+urWfgpCngjNgWgWzT4EKE0ix/TySkkvzEYEKJRGacBbMgrOfD9Dzn0bPkVlI",
	"CWYagZmJJCjBmYKgFwjJBUhNQLn1GhPa3emXLMWsLwFHeEEBwa2gmGEziJSAkMQkRJojnRCFeBhmUgIL",
	"zfZwi1NBIZgF5wmg7xhO4TsUE6ARIgpJ+JgRCRFaZBrdYIUY10hIviIRREEv0LkwS5WWhC2DdS8gTGls",
	"du5oeHE2RxJisIJRzKVTptLOHXyLbkM7qobjyR5Mf3z2vA8/vVj0x5Nor4+nPz7rTyfPno2n4+fT0WgU",
	"9IKYyxTrYBZkkvQroT59lcY6Ux57np+fIjeIQh61tJmORtVOhGlYgjRbaaKp59xvEy41Str3o7I0xTJH",
	"PEY6AWPRBYW0deQ5W2FKIjRnItM+1d0/7jYziYBpEueELa0gZ2S7sikr0Vqo2XAYhemg+O8g5GlpdeJU",
	"6ZNClV3Nu+4FpQMFs3dBIdbZ6X01my8+QKjNiU6dY3kC5eeM0tLvbHTwTIaAJAgJCpi2nt4JllAC1nCl",
	"Seox1DlJQWmcCnSTACuvwQkwnh4TqTSSsCRKg7TeXp07whr6dlvPvURECYrzKxNKnw3UYjIyk4ugqPVo",
	"3dGv2QJ+J1KjtyBXJAR0Ws/q6AAsEpwwvcWS5TC6OHtjji+hff7907mJfhyGoBRZUL+3KDFueQsWZLga",
	"D1fphot4cSLyuC4jH7PKZwnIyiCeI9fqfDEmZMQLXSloHGGNjWL/lBAHs+AfwxrRhwWcD0sljsv5617g",
	"v+viQPZui0i/8yTX2QJWROr+eLLn09D4tvV0D2C9IUobIfUcpDIhuNQQNdC2EL+JAO+KWAl6QQQU7Ecm",
	"jJubQCUaUityCwYFWEqcm78F1oknzZXxaoYb99s6fOl8O4N8F8vd4a78wHieC3sLlQmMPSqP53EMUhmF",
	"WJYae1gvNte7wDYNh5xpTJhVWmku8dImZx4ZA9WnsMs6mjlT/k0golhp5HbYFYQ2gNf6u3XRBjJs2KuD",
	"x73gto9B9EuwDWZaZtBAaeNx3dOc4iVhRlVEC4+sLraDzwxu9ZXAS7jS/BqYxzTm39Z7JWhJYFXmMbMS",
	"mZVGgASVUa1a3gT5a/Gfg/mz+Yej/HhyMTo5/3PvzR8X09/+mOvj89fXx/k4OTm8mLw5/3d+8uHP25PD",
	"o72Tw/2b44PXL3w3WB9i9qmOh11gohsm6ztS33EDhNq22I8iYj4xRSVSIbzgmd5MGW0bmwTG2ZXlMJ09",
	"XwFfSiwSEiI3z3IdX0ZwsAJtI2eqD1jp/thnsdJvPmuoEh0OsMAh0fldtOzAkkNdoxymJUurqVQXWBPA",
	"VCe5T82/OPMYZn+FCcULQonOkZmCuETG5CEwDXIbhtUz+gtvVG699zPLM9yZfABajyKBc8qxA3VcwdlW",
	"B/hGR/4mHflNFA6W7cxLBpdsHrdqpB46PDhGN4RStARmYwgZd8KZ5inWJMSU5oNL9v/DaAaX7EJBhLBy",
	"SI11JjFF15Bbs6VYh4mBcbglSpsP2XButWmKb5TokSnR4JId4TBpFl8NLDLzQbZsWNzg/dOoDVJz73zm",
	"rOy5+C7LjlTQi2OTBLwm6eDvE6x0HtUlRaPI35U/baMDrbxYTKp9r1W7lwS65WatGTtw6ELE7r7V4Tbb",
	"rR4WUxBh7gJ9zqS5xvQqFJmPK2tM0cHpBQq5BIWwozDtZDnZ0rqy26aQcplv29mN+rcNxucvvS0quy/z",
	"ck+3K8vShcUaZGa16OX4Ll1L7NiybTG8RduJT9suO1vbfmbMbSvJ4FZoCMy6tyHRJPjNsLWUpY9a/olZ",
	"hFLM8BJSS2HjzioDtucGgy3hMcqamcoLDG0cjim/MRk3gpgwiBCxdeQlM7oBSzALnVDjTVxh6kCakhAK",
	"wHPpPtgXOEwATQYmdDNJG/Tq5uZmgO3wgMvlsFirhm/mB0cnb4/6k8FokOiUNlqhgc8sQS9YgVTOdqsx",
	"piLB4yKVMyxIMAv2BqPBNHA4Zd1+6Ai8+VyCh0X+YodRmEB4baF0250EDcYwj6qVgS1XLMZbeZPRqLx0",
	"cKwVC0FJaNcNPyjH0R1Sma92kNZoVbscv97V4zZI6K92XtEv3jiq2RIvlYGnwkDvzeRhq1j1GuwMdCaZ",
	"Qriq0mso7JQUCt0QnSBe8uGYUA32CJvWNIzrtFnuY4lT0FaTdx3qb7dpSFnkm2SMmHkfM5B52cCYlV3k",
	"2vgdq24KOsa3JM3SBtYUHQPLXYSjID5RKb517QlF/vLKrGCpK7RuXQjXEXFw7hPT6IDcda73/6OT7pJs",
	"bU/H44ZvM1t7xRmt2bSJ2emdOhTPGv/6Ml3cW5lHiZc4sg9SoGzpHEGMM6ofTv4Fg1sBoakeoJjTjExb",
	"buDGO4VqxGfFet4bCsSV3kZmwBT1DG46UYi4LLqACLO6euLMMO6zDVJOIkgFNzaZXbI+MkWpKdkiDu4J",
	"zy7vFZLeniJgWuZmoat5ouYiO7fAAIVTGDJeKTU/7Ll3pXJ9QbO2rY9IbF+LdGuHdirDhCr0fchZTEmo",
	"fyi2qudv2dDI+uxWHcQ6sOdtsO07IatqCVSXMj+0MV7be7MY8AW845KVM36Gr7vAt27/kkf5vcd8q/W0",
	"bvPegsZ+ddypai9P2FX5u/At9L2EftPKPxg0mIzGj6NVETHoexNKHbUeFCDLJ2P3Tmulv3g46QdFmKF+",
	"0R+SzaDFVAKOTHWDMmPRXjCdTB5Oud+NYRwqwG0IokxgTy2JNJKAr7HazSYtvjf8VFk8WrsMYztXnlyT",
	"8hV42scoljy1kF64ct6BzEO7566Q2W11bDTqkeaoarBZtLTtiZodVScKNpHpi0G0hWJTz+NVqZNTKEKq",
	"4j00f7Rwnh/aviUlEDkdpg+nQ2URwxpinrHoKUaNc8mGO98dMz1/UfQKtC8iFjkiWpWvAPPDTkC8An1v",
	"0fDAMXD/mfzJVg/fomnXaHJxID4TQoZidBvb3QJlM55sjwua1IAUP3rAOkFpprR7I2pt0ljcCb99IWh+",
	"r+moeOb56qH49Tj9Y/H4nfj7k0iqDY786ADwqDS9TcxNtsOM66TRmXuKGFUCza4suXgLLUHBtbaLnwgE",
	"JhqLRZ1f7242kZsd/PrtuQMPQbcj2GpS+9YWPdz1+/V/AwAA//9B7cuJSi4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
