// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPbNhL+KxhcZ5pe9W43afTlxrXTRm3s+By7nV7i80DkUkICAggAymZ9+u83APgq",
	"QrbcSZ3M3H2TSWB3sdh99tmlb3EkUik4cKPx9BbraAkpcT9fKCWU/RGDjhSVhgqOp/jsx0P07PvRM2Q3",
	"Mkq4QWBXIgVaCq4B97BUQoIyFLTfbwhlXUkvs5TwvgISkzkDBDeSEU7sS6QlRDShETICmSXVSERRphTw",
	"yIqHG5JKBniKz5eAvuYkha9RQoHFiGqk4GNGFcRonhl0TTTiwiCpxIrGEOMeNrm0W7VRlC/wuocp14ZY",
	"yR0LL85mSEECTjFKhPLGVNb5g2+xbeje6uF4sgf73z191ofvn8/740m81yf73z3t70+ePh3vj5/tj0Yj",
	"3MOJUCkxeIozRfuV0pC92hCT6YA/z89PkX+JIhG3rNkfjSpJlBtYgLKiDDUscO43S6EMWrbvR2dpSlSO",
	"RILMEqxH5wzS1pFnfEUYjdGMy8yETPcP7nYzjYEbmuSUL5wi72S3s6lraYzU0+EwjtJB8XQQibT0OvWm",
	"9Glhyq7uXfdwGUB4+hYXar2fLqvVYv4eImNP9BIIM8vAZbjn5XVoyhcMjOA2S0Smom6WSBISc0i44DQi",
	"DNn3pe8bQhoO8ZZY+0n8mrMcT43K4CEB1LQ5IDsPuqvtkh6+6ROQ/cpEfzQDimvr0MLKyx6WLFOEVcKt",
	"wspNpen2QcaIah6vtADUikZQJLYa2DigYlgss4adFq+6B/0xY6yEBFV5EymQCjRw40Coc0ORAmLgytA0",
	"EMPnNAVtSCrR9RJ4mSFegQWhhCptkIIF1QaUA6IqJGNioO/E7nB5MdWSkfzKot69mFosRnZxgV+1Xa0b",
	"/iWbw69UGfTG+xWd1qs6NgCPpaDcbPFs+RpdnL2y7lDQ9sfB6cwCNYki0JrOWTixtRy3EptIOlyNCZNL",
	"Mh6u0o2cDpnpY+Fqp3BvwFrXOdaf+S6XQ+MAunH6MatgjYKqLiLg6lrng8tGRuNdTEzBkJgYYg39SkGC",
	"p/hvw5oEDAsGMCyNOi7Xr3s4HHPFAV2MFV6882QfsjmsqDL98WQvdG0251wGBu7sFdXGKqnXIJ1JKZSB",
	"uFGgC/WbReNtkcO4h2Ng4H5k0qafBSRqIHUqt5QtTJQiuf07jNVnJY44qK7vu3X4Mr525gX3o7m7sKsV",
	"KO3s6BRz9x4V78sbarrIX9lp6ck29Jcph3sljuMp/vfq7aj//PLbJ+7df+ZgyDf/cI/+/lWQsnhtV+H6",
	"f25tEEltk73DCi1EkoDasCl9CC86c6CrCmZZFTeepTYiWpDsgyG20dDM/saKe6/Di/iTVYIRbVBpxJ+r",
	"EBsExqVsA7E37qITPpcPLeh1QN+WP69ovG5V+GoNbpV02S0x4aJeLWyWdQsFXQ+fkgXl1n2IFVDRVN4u",
	"6BxuzJUkC7gy4gMEUufcPnawosAoCquSk9qdyO60ChTojG1kDeQ/y38dzp7O3r/IjycXo5Pz3/de/Xax",
	"//q3mTk+//nDcT5enhxdTF6d/zM/ef/7zcnRi72To4Pr48Ofn4diuz7E9LYGql3wu4tf6wCN7aD99BaT",
	"OKbWEYSdNtzmg67tp4NqJSrLCyJzkZnNktr2v00swa9cr9Lx/U8gForIJY2QX+d6mhCd8LUA2heQ6T4Q",
	"bfrjkDfLWL7XiSWkHxJJImryu2Dm0DWBpi5NhO3CLbZS6x7+Q/CAYw5WhDIyp4yaHNklSChkXR4BN6C2",
	"FZ56RX++A49f93Dn8NsrXlQsQZR7zArxZyMMYVeRzEKJZghDh6cXKBIKNCL+jG1mONnSwzqxKaRC5dsk",
	"+7dhsXh8/kOwV3VyeTA4vVSepXNXoJBd1Yq/8V22aiMUWWwVW7zeYu0kZG33+tZusJEI17gIbkhkwXK9",
	"mblHh8cdsub4eR+1yibhMUoJJwtIXYwnnV168I6f28Lt2L011q7UQTpY9EGF7ISJa0Q0iiGhHGJEXWF8",
	"x61twJeER16pjSahCRu8s7HFaARcOyd6WooPJImWgCYDS5syxRq9xPX19YC41wOhFsNirx6+mh2+OHnz",
	"oj8ZjAZLk7LGTASH3IJ7uOJZNTPynJUTSfEU7w1Gg31PlpYu7MuWdHqLF2C2tiHREqIPrtZsuxPcoMaz",
	"2EGkeVk3/X765lRORqPy3sF3aURKRiO3dfhee5roQe4+CHxZNtSd2Hn9iwu8Yi60cRIbo2TRavnt4mGr",
	"kAX9cQYmU1wjUlXwmoBVFLESg66pWSIhC8BNKDPgcmLTWZYunDapAFEkBeMsedtpY52YhpZ5vtlUULvu",
	"YwbKQncRgS1KFegk1r1NRcfkhqZZ2oCSgk0gafVblAirSsmNpy6a/tHWGUNCMmYKDEq9gvIvyou/uujU",
	"Na6mP9KzKo/qIXMaLOqu81/+hYHa4oWBcH2TuXlDkrG6RNvU3b/ThmLM+e3DbPGz84ARP5DYDahBuxJb",
	"3dVj6b/gcCMhsvwYijXNDHbtNWkMx3Qjjyv6cmkJqdBmW6sFChHE4bqTrZap+O4GEY7ghmpjGbXgMHjH",
	"W/WGastjUimsT6bveB/NEj9hiAX4kb7b3is0vTlFwI3K7Ubf48fNTW5tgRWapDDkojJqdtTzc+Zyf9F/",
	"bdsf08RNj01LQruiEco0ehIJnjAamW8KUfX6LQKtrntFdZDt0J23MWq5E9pel1BZXcrsyOV47e+WBVsS",
	"3g2b6mDcHEMFE9+F/Q8izj95zvtQr/te26SsHwFrQilWlewijtATBf2mR7+xmT8ZjR/XmiIr0BObLh1z",
	"HhUEy89E/tuM0/788bQfFqmE+sXIUjUTkzA37LUkNNPgjJtMHs+4X61jfObDTQSyLFJfWqFoAH3og0G3",
	"YrS4Xz0qmsVrX0XcNDZQT1KxAkS6lSRRIi2+hblQzjuweORk7gqL3Sn9RtOOjEDV0NghopsC1wyoOhHe",
	"RKIHA2ULtfYDQ67SJm9QjHTFbVj+2dJ5duQmyIxC7G3YfzwbKo9YZpCIjMdfYtb4kGyE89050ws3SD+B",
	"CWXEPEfUaJT5QJ4dhdrFT5YNj5wDj1O5v4gO4f/ZtGs2+TyQ96SQpRjdT5bdJmQzn9w4C5rUgBYfbIhZ",
	"ojTTBqXERMuWkMbmTvodSMnyT1qOik+Xf3kq/o/y9i+iqDY48mcHgM9K09vE3FY7woVZNqZ0XyJGlUCz",
	"K0suvpWXoOCn2K1/fcE2J4utnU/9m1Pj5si+/q+KDkjg7uyvNZUO7S3/0epy/d8AAAD//5akpX1EKgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
