// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXMbtxH+Kxg0M3EavouxY37pKJQTM7FkVaaSSW1VA97tkbBxAAzgKDEq/3sHwL3y",
	"QL1kHNkz7TfqDthdLHaffXZPNzgSqRQcuNF4coN1tIKUuJ8vlBLK/ohBR4pKQwXHE3z24xQ9+37wDNmN",
	"jBJuENiVSIGWgmvAHSyVkKAMBe33G0JZW9LLLCW8q4DEZMEAwbVkhBP7EmkJEU1ohIxAZkU1ElGUKQU8",
	"suLhmqSSAZ7g+QrQ15yk8DVKKLAYUY0UfMyoghgtMoOuiEZcGCSVWNMYYtzBZiPtVm0U5Uu87WDKtSFW",
	"csvC87MZUpCAU4wSobwxpXX+4Hts67u3uj8cHcD4u6fPuvD980V3OIoPumT83dPuePT06XA8fDYeDAa4",
	"gxOhUmLwBGeKdkulIXu1ISbTAX/O56fIv0SRiBvWjAeDUhLlBpagrChDDQuc+81KKINWzfvRWZoStUEi",
	"QWYF1qMLBmnjyDO+JozGaMZlZkKm+we3u5nGwA1NNpQvnSLvZLezrmtljNSTfj+O0l7+tBeJtPA69aZ0",
	"aW7Kfd277eAigPDkLc7Vej9dlKvF4j1Exp7oJRBmVoHLcM+L69CULxkYwW2WiExF7SyRJCRmSrjgNCIM",
	"2feF72tCag7xllj7Sfyasw2eGJXBQwKobnNA9iborqZLOvi6S0B2SxP90Qworq1DcysvOliyTBFWCrcK",
	"SzcVptsHGSOqfrzCAlBrGkGe2Kpn44CKfr7MGnaav2of9MeMsQISVOlNpEAq0MCNA6HWDUUKiIFLQ9NA",
	"DM9pCtqQVKKrFfAiQ7wCC0IJVdogBUuqDSgHRGVIxsRA14m9x+XFVEtGNpcW9e7E1Hwxsotz/Krsatzw",
	"L9kCfqXKoDfer+i0WtWyAXgsBeVmj2eL1+j87JV1h4KmPw5PZxaoSRSB1nTBwomt5bCR2ETS/npImFyR",
	"YX+d7uR0ENjjANZw+jErQYaCKt0SOHhl1INBPKPxfW4zBUNiYog19CsFCZ7gv/WrktzP63G/MOq4WL/t",
	"4HAE5Ad0N57Dxa0n+5AtYE2V6Q5HByEn2gxw+RAAjFdUG6ukWoN0JqVQBuJauczV70L42zyjcAfHwMD9",
	"yKRNBgsP1EDqVO4pIpgoRTb27zBynhVZ7YCzuu/G4YuQvHeVvhtb3YVdrkFpZ0ertLr3KH9f3FDdRf7K",
	"TgtPNoG4SADcKVAVT/C/128H3ecX3z5x7/6zAEO++Yd79PevggTCa7sMV+O5tUEklU32DsvcFUkCasem",
	"9CEs5cxBoMp5XllqeJbaiGgApA+G2EZDpa2x4s7r8CL+JGYzog0qjPhzeL1DJ1zK1vBz5y5a4XPx0PJa",
	"BfRN8fOSxttGvS3X4EaBlW3AD5fYcmG9yFooaHv4lCwpt+5DLIeKuvJmeeVwbS4lWcKlER8gkDpz+9jB",
	"igKjKKwLhmh3IrvTKlCgM7aTNbD5Wf5rOns6e/9iczw6H5zMfz949dv5+PVvM3M8//nD8Wa4Ojk6H72a",
	"/3Nz8v7365OjFwcnR4dXx9Ofn4diuzrE5KYCqvvgdxu/tgFS2UL7yQ0mcUytIwg7rbnNB13TT4flSlSU",
	"F0QWIjO71b/pf5tYgl+6zqHl+59ALBWRKxohv851GKHi7msBNC8g010g2nSHIW8WsXynEwtInxJJImo2",
	"t8HM1LVkpipNhBVkvGpg2tVwL9Ht4D8EDzjmcE0oIwvKqNkguwQJhazLI+AG1L7CU63oLu7Bqrcd3Dr8",
	"/ooX5UsQ5R6zQmzWCEPYZSSzUKIZwtD09BxFQoFGxJ+xydNGezpKJzaFVKjNPsn+bVgsHs5/CHaOTi4P",
	"BqeXyrN04QoUsqsa8Te8zVZthCLLvWLz13usHYWsbV/f1o0ZEuHaCMENiSxYbncz92h63CJrji13UaNs",
	"Eh6jlHCyhNTFeNLapXvv+NwWbse1rbF2pQ7SwbwryWUnTFwholEMCeUQI+oK4ztubQO+IjzySm00CU1Y",
	"752NLUYj4No50dNSfChJtAI06lnalClWY/ZXV1c94l73hFr28726/2o2fXHy5kV31Bv0ViZltQkFDrkF",
	"d3DJsypm5DkrJ5LiCT7oDXpjT5ZWLuyLBnFyg5dg9vbA0QqiD67W7LsTXKPGs9hBpHlZteB+FuZUjgaD",
	"4t7B90xESkYjt7X/Xnua6EHuLgh8WbS3rdh5/YsLvHxKs3MSG6Nk2WjA7eJ+o5AF/XEGJlNcI1JW8IqA",
	"lRSxFIOuqFkhIXPATSgz4HJi11mWLpzWqQBRJAXjLHnbaiqdmJqWxWa3qaB23ccMlIXuPAIblCrQSWw7",
	"u4qOyTVNs7QGJTmbQNLqtygRVpWSa09dNP2jqTOGhGTM5BiUegXFX5Tnf7XRqW1cRX+kZ1Ue1UPm1FjU",
	"bee/+AsDtcELA+H6JnPdf5KxqkTb1B3fakM+dPz2Ybb4SXbAiB9I7MbFoF2JLe/qsfSfc7iWEFl+DPma",
	"ega79prURlW6lsclfbmwhFRos6/VAoUI4nDVylbLVHx3gwhHcE21sYxacOi94416Q7XlMakU1ieTd7yL",
	"ZomfMMQC/IDdbe/kmt6cIuBGbexG3+PH9U1ubY4VmqTQ56I0anbU8VPfYn/ef+3bH9PEzXJNQ0KzohHK",
	"NHoSCZ4wGplvclHV+j0Cra47RbWQberOWxu13AptrwuoLC9lduRyvPJ3w4I9Ce+GTVUw7o6hgonvwv4H",
	"EW8+ec77UK/6XtukbB8Ba0IpVpbsPI7QEwXduke/sZk/Ggwf15o8K9ATmy4tcx4VBIuPNv5LidP+/PG0",
	"T/NUQt18ZKnqiUmYAhLbRgZlGpxxo9HjGferdYzPfLiOQBZF6ksrFDWgD43v2xWjwf2qUdEs3voq4qax",
	"gXqSijUg0q4kiRJp/mXKhfKmBYtHTuZ9YbE9pd9p2pERqBwaO0R0U+CKAZUnwrtI9GCgbKDWODDkKmzy",
	"BsVIl9yGbT5bOs+O3ASZUYi9DePHs6H0iGUGich4/CVmjQ/JWjjfnjOdcIP0E5hQRiw2iBqNMh/Is6NQ",
	"u/jJsuGRc+BxKvcX0SH8P5vum00+D+QdKWQpRvuTZbsJ2c0nN86COjWg+QcbYlYozbRBKTHRqiGktrmV",
	"fodSss0nLUf5p8u/PBX/R3n7F1FUaxz5swPAZ6XpTWJuqx3hwqxqU7ovEaMKoLkvS86/lReg4KfYjX9E",
	"wTYn862tT/27U+P6yL76r4oWSOD27K8xlQ7tLf7t6WL73wAAAP//GmlODdIpAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
