// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ProviderServiceType.
const (
	ProviderServiceTypeContainer ProviderServiceType = "container"
	ProviderServiceTypeDatabase  ProviderServiceType = "database"
	ProviderServiceTypePod       ProviderServiceType = "pod"
	ProviderServiceTypeStorage   ProviderServiceType = "storage"
	ProviderServiceTypeVm        ProviderServiceType = "vm"
)

// Defines values for ProviderRegistrationServiceType.
const (
	ProviderRegistrationServiceTypeContainer ProviderRegistrationServiceType = "container"
	ProviderRegistrationServiceTypeDatabase  ProviderRegistrationServiceType = "database"
	ProviderRegistrationServiceTypePod       ProviderRegistrationServiceType = "pod"
	ProviderRegistrationServiceTypeStorage   ProviderRegistrationServiceType = "storage"
	ProviderRegistrationServiceTypeVm        ProviderRegistrationServiceType = "vm"
)

// Defines values for ProviderResponseStatus.
const (
	Registered ProviderResponseStatus = "registered"
	Updated    ProviderResponseStatus = "updated"
)

// Error RFC 7807 compliant error response
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference for this specific error occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int `json:"status,omitempty"`

	// Title Short human-readable summary of the problem
	Title string `json:"title"`

	// Type URI reference identifying the error type
	Type string `json:"type"`
}

// Provider Full provider resource representation
type Provider struct {
	// CreateTime Timestamp when the provider was first registered
	CreateTime *time.Time `json:"create_time,omitempty"`

	// DisplayName Human-readable display name for the provider
	DisplayName *string `json:"display_name,omitempty"`

	// Endpoint Full endpoint URL where the provider API is accessible
	Endpoint string `json:"endpoint"`

	// Id Unique identifier for the Service Provider
	Id openapi_types.UUID `json:"id"`

	// Metadata Additional metadata about the provider
	Metadata *ProviderMetadata `json:"metadata,omitempty"`

	// Name Unique name of the Service Provider
	Name string `json:"name"`

	// Operations List of operations supported for this service type
	Operations *[]string `json:"operations,omitempty"`

	// Path Resource path identifier
	Path *string `json:"path,omitempty"`

	// ServiceType Type of service this provider offers
	ServiceType ProviderServiceType `json:"service_type"`

	// UpdateTime Timestamp when the provider was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// ProviderServiceType Type of service this provider offers
type ProviderServiceType string

// ProviderList Paginated list of providers
type ProviderList struct {
	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string     `json:"next_page_token,omitempty"`
	Providers     *[]Provider `json:"providers,omitempty"`
}

// ProviderMetadata Additional metadata about the provider
type ProviderMetadata struct {
	// RegionCode Geographic region code where the provider operates
	RegionCode *string `json:"region_code,omitempty"`

	// Resources Resource capacity information
	Resources *ResourceCapacity `json:"resources,omitempty"`

	// Status Current operational status of the provider
	Status *string `json:"status,omitempty"`

	// Zone Availability zone or datacenter identifier
	Zone *string `json:"zone,omitempty"`
}

// ProviderRegistration Registration payload for a service provider
type ProviderRegistration struct {
	// DisplayName Human-readable display name for the provider
	DisplayName *string `json:"display_name,omitempty"`

	// Endpoint Full endpoint URL where the provider API is accessible
	Endpoint string `json:"endpoint"`

	// Id Optional unique identifier for the Service Provider.
	// If not provided, DCM will generate one automatically.
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Metadata Additional metadata about the provider
	Metadata *ProviderMetadata `json:"metadata,omitempty"`

	// Name Unique name of the Service Provider.
	// Used as the natural key for matching existing registrations.
	Name string `json:"name"`

	// Operations List of operations supported for this service type
	Operations *[]string `json:"operations,omitempty"`

	// Path Resource path identifier
	Path *string `json:"path,omitempty"`

	// ServiceType Type of service this provider offers.
	// Each provider registration is per service type.
	ServiceType ProviderRegistrationServiceType `json:"service_type"`
}

// ProviderRegistrationServiceType Type of service this provider offers.
// Each provider registration is per service type.
type ProviderRegistrationServiceType string

// ProviderResponse Response payload after provider registration
type ProviderResponse struct {
	// Id Unique identifier for the Service Provider
	Id openapi_types.UUID `json:"id"`

	// Path Resource path identifier
	Path *string `json:"path,omitempty"`

	// Provider Full provider resource representation
	Provider *Provider `json:"provider,omitempty"`

	// Status Registration status
	Status ProviderResponseStatus `json:"status"`
}

// ProviderResponseStatus Registration status
type ProviderResponseStatus string

// ResourceCapacity Resource capacity information
type ResourceCapacity struct {
	// TotalCpu Total CPU cores available
	TotalCpu *int `json:"total_cpu,omitempty"`

	// TotalMemory Total memory available
	TotalMemory *string `json:"total_memory,omitempty"`

	// TotalNode Total number of nodes
	TotalNode *int `json:"total_node,omitempty"`

	// TotalStorage Total storage available
	TotalStorage *string `json:"total_storage,omitempty"`
}

// ListProvidersParams defines parameters for ListProviders.
type ListProvidersParams struct {
	// Type Filter providers by service type
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// MaxPageSize Maximum number of results per page
	MaxPageSize *int `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// PageToken Token for pagination
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateProviderParams defines parameters for CreateProvider.
type CreateProviderParams struct {
	// Id Optional provider ID for idempotent registration
	Id *openapi_types.UUID `form:"id,omitempty" json:"id,omitempty"`
}

// CreateProviderJSONRequestBody defines body for CreateProvider for application/json ContentType.
type CreateProviderJSONRequestBody = ProviderRegistration

// ApplyProviderJSONRequestBody defines body for ApplyProvider for application/json ContentType.
type ApplyProviderJSONRequestBody = Provider
