// Package resource_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package resource_manager

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZbXPbNvL/Kjv4d6bJ/EU9WXUavblJLbdhLnZ8sdNOLva5MLmUkIAAAoCWVY+++w0A",
	"khIlSnV6E19e3DuRBHZ/2Iff7kL3JJG5kgKFNWR8TxTVNEeL2j/FwlgqEozTM2pn7k2KJtFMWSYFGZN3",
	"gn0uEFiKwrKMoQaZgZ0hsHIj6RC8o7niSMZkMDzA0Q+HzyL88flNNBimBxEd/XAYjYaHh4PR4Nmo3++T",
	"DmFOsnL6OkTQ3O1kNQ7SIRo/F0xjSsZWF9ghJplhTgN4a1G77f/6QKM/+tHzqyflj+jqvt85HCyr90//",
	"9h3pELtQTryxmokpWS6XlTR/+mOtpd4+9Nufj+DZj/1n4CzHGRUW0K0EjUZJYdyhlZYKtWVown5LGd+W",
	"9LLIqYg00pTecAS8U5wK6j6CUZiwjCVgJdgZMyCTpNAaN216MUP43lnpe8gY8hSYgcpAcFNYmFMDQlpQ",
	"Wt6yFNPtU3dq87Y4+G0MGjP0iiGTOoCp0YWD78DW819N74F+z6TOqSVjUmgW1Urb8BpLbWFa7HlxcQbh",
	"IyQybaAZ9fu1JCYsTlE7UZZZ3nLu85nUFmZN/5giz6leVDGutLzhmDeOHItbylkKsVCFbYMeXuw3c5lO",
	"CyamXlEwst+5rmtmrTLjXi9N8m75tpvIvLI6C1AiVkJ5qHmX6xn2gZRqg52u6tXy5iMm1p3oJVLexg3h",
	"feUOw8SUo5XCZYksdLKdJaqVYo6okIIllIP7Xtl+TciaQQISh5+mbwRfVAzx8ABax9wie9FqrqZJOuQu",
	"oqiiGuKKmIwzaInyqkMULzTltXCnsDZTTW5MTAtO9frxKgSob1mCZWLrrosDJnvlMgfsPKy4WCiMd6b4",
	"zwXnUMryQVaTd21l0Kg0GhTWk9OW5xKN1OK1ZXmL/AuWo7E0VzCfoWhUB09OGdPGQhCRrsdpSi1GXuYD",
	"PMrSh1SnQGAIpWHAWQbi/6BW5fTuNYqpC9zDgw7JmageB50vL0d/esr2FHlbuclnyOq4jQOVHo6czKhy",
	"wEOp+c+BlUF4HQr2JsJTmuMabfqlDXSfihu8ZdpGg+FBK+MrTJxYmqbMyaT8bC0CA6gNBi9dXJWqUFYz",
	"ybmcO2KVokZkCqWktpg20uBSlK0APPn15Fxh0oEjKSxlAnV4nFBLb6jB8CQ1HPHC2PD1afdSkBa23MU8",
	"54Em97VPb49fTN4/xBmFSv96OnJqLAQJfzUbNypIMzZKX159KW22xq/p3Vc/r1m6bJBq6wbSYNRdS/YT",
	"bPuuHXz7mhm77YQzOmXCWRg4M9Z5vT7RFrmuvrgHi7n/8Z3GjIzJ//VW7XuvjNdeG+2vyhTVmi7cs8A7",
	"e63oFK+t/ISiJVTca8+ZGq1meFs1JG4nuJ0OuUZTcNuslrh4pf55FB/GH48XJ8N3/dOL9wevf3s3evNb",
	"bE8uXn06WQxmp5N3w9cX/1icfnx/dzo5PjidvJifHL16/oAS6xt1JjLpi49LysQZebnJAZOjEzg/g5of",
	"T6igU8xRWHhxFkMER67qOF6gIoV89VVmdYloVETTvRQXrgF225k7rFtudtcUyLicAzWQYsYEpsB8yl0K",
	"Bw3FzK3xGp3PpaE80AZnCbpBYnxfTUAvFE1mCMOuo+NC87X+bz6fd6n/3JV62iv3mt7r+Oj49Pw4Gnb7",
	"3ZnN+Vq7W7PjWRnbT87Pnu6yE+mQW9QmmPR2QLma0YETJhUKqhgZk4NuvzsioT758Ky6kPE9maLd2Wgl",
	"M0w++Qjb7yrilWnvqzglY/IL2perbi+MXV7xsN+vggKFV0yV4iX99z4a6eN8NTLuy6OXVSe1FVhv/u6j",
	"shwINs7jAphOG72eW9zgDRM10rrVRm/RFloYoDVJtHZpBubMNcYq1EXIGLfoE2fTaI6L4nWeWZv1P2y1",
	"hV5MQ2U1m38uUC9Ww3n5aWXTrfTdlH1C71he5CCK/CbcGZQkAgq1J5YdqnJ6FxjLsD+aOlPMaMEtGQ/c",
	"nJcHBdUTE+XT9gS4DW7FeiqwdOh42+Cskee+8199xRjdVXJagva8SBI0Jis41HHh0ni0F0455f7/l8EK",
	"VyctIH6iqb+fQOPbodptj6X/ncA7hYkrvViuWc9jZzuguwYis5badeG/cu2vbKvyvrogUBA4XzVZMgPa",
	"EN+9FG/K5OWLsl9dAIWEMxQ2osawqSsd8QQuxS2jvtr8ztLfwYcj1GnchThr3PV0Qq1xylDDnHEOUxTO",
	"9QhUQDwJ1abJEgH12lC0lyYq5A6dy5lWu+1IH5aSPbd3X3h1dxWaTjT2J5kuvmZ+hbBq3kIut1J88PUh",
	"ND1RtxzVKP3YqV3dfYULJ6/9+eNpP5Ii4yyxENVhF0+AcjerLFzbVRjfBY+Gw8cD9aszSOgw8S5BVVHu",
	"t0Z7FVOJPTTVzn17GpvVbBany8COHC22NTq5vG1o3yKlid+6m5TajLJa0tv4H6OlIo+2YdUJFXCnYOoC",
	"yhf/teyKJ/6+grMqw0ePiaG0iCsymSxE+i0Gc4iVjXBqLdutbfcvaBuJcLMAZg0U4TIxnrTNIl8xMPuP",
	"XUe+iTbxf9H+0GjfDNeNMXEHazsRvisMURouFHpUsd5qwL+qt25dVrYP6nW4mO1/bsn2oNW4A2jbW/2T",
	"cbX8dwAAAP//93VIN6YeAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
