// Package resource_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package resource_manager

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZbXPbNhL+Kzu4zjSZE/Vm1Wn05SaV0oa52PHFdju9WOfC5FJCAgIIAOqlHv33GxAk",
	"JUqU6vQmvnzoN5EEdhe7zz67C92TSKZKChTWkOE9UVTTFC3q/CkUxlIRYRhfUDtzb2I0kWbKMinIkFwL",
	"9ilDYDEKyxKGGmQCdobAio2kRXBJU8WRDEmvf4KD706fBfj987ug149PAjr47jQY9E9Pe4Pes0G32yUt",
	"wpxk5fS1iKCp28kqO0iLaPyUMY0xGVqdYYuYaIYp9cZbi9pt/897GvzeDZ5PnhQ/gsl9t3XaW5fvn/7j",
	"G9IidqWceGM1E1OyXq9LafnpX2ot9f6h3/04gmffd5+B8xxnVFhAtxI0GiWFcYdWWirUlqHx+y1lfF/S",
	"qyylItBIY3rHEXCpOBXUfQSjMGIJi8BKsDNmQEZRpjXu+vRqhvCt89K3kDDkMTADpYPgLrOwoAaEtKC0",
	"nLMY4/1Ttyr3NgT4XQgaE8wVQyK1N6ayzh/8gG2d/KvpPDDuidQptWRIMs2CSmmTvcZSm5kGf15dXYD/",
	"CJGMa9YMut1KEhMWp6idKMssbzj35UxqC7N6fEyWplSvSowrLe84prUjh2JOOYshFCqzTab7F8fdXKTT",
	"iolprsg7Od+5rWtmrTLDTieO0nbxth3JtPQ686YErDDloe5db2fYe1Ko9X6aVKvl3QeMrDvRK6S8iRv8",
	"+zIchokpRyuFyxKZ6Wg/S1QjxYyokIJFlIP7Xvp+S8iWQ7wlzn4avxV8VTLEwwG0bXOD7FWju+ouaZFl",
	"QFEFlYkbYjLOoYWVkxZRPNOUV8KdwspNFbkxMc041dvHKy1APWcRFomt2w4HTHaKZc6wS7/iaqUwPJji",
	"P2acQyErB1lF3pWXQaPSaFDYnJz2IhdppBZvLUsb5F+xFI2lqYLFDEWtOuTklDBtLHgR8TZOY2oxyGU+",
	"IKIsfkh18gSGUDgGnGcg/B9qVUqXb1BMHXBPT1okZaJ87LU+vxz94SmbU+RdGaY8QzbHrR2oiHDgZAZl",
	"AB5KzX9sWAHCW1+wdy08pylu0Wa+tGbdx+wO50zboNc/aWR8b/1tM31ebqP3WAcyTxuFK4ycUBrHzEmk",
	"/GIL3v7EzQrLOuhrdiI5lwvH2lJUdphMKaktxrUcuxFFnwFPfj67VBi1YCSFpUyg9o9jaukdNeifpIYR",
	"z4z1X5+2bwRpoOJMxX8+Dzk1FryEP5uGO6WjFrRdjBRun3wufTbi2HTuy5+3LF7XyLVxA6kx66Elx4m2",
	"edcB3n3DjN2PyQWdMuEcDpwZ6yBTnWiPZDdf3IPFNP/xjcaEDMnfOps2vlNAq9NE/5tyRbWmK/cscGlv",
	"FZ3irZUfUTQgx73OuVOj1QznZWPidoLb6SzXaDJu61UTV6/Vv0fhafjh5eqsf909v/r15M0v14O3v4T2",
	"7Or1x7NVb3Y+vu6/ufrX6vzDr8vz8cuT8/GLxdno9fMHlNq8YWcikXkRcvkTOSevd9N1PDqDywuoePKM",
	"CjrFFIWFFxchBDBy1celMBUxpJuvMoHLpspo2jfiyjXCbjtzh3XLzeHaAgmXC6AGYkyYwBhYnoE3wpmG",
	"YubW5BpdzKWh3Gc4ZxG6gWJ4X05CLxSNZgj9tqPlTPOtPnCxWLRp/rkt9bRT7DWdN+Ho5fnly6Df7rZn",
	"NuVbbW9FZBcFtp9cXjw95CfSInPUxrt03qNczWjPCZMKBVWMDMlJu9seEF+ncniW3cjwnkzRHmy4ohlG",
	"H3OEHQ8VyZXpPFZhTIbkJ7SvNl2fH79yxf1utwQFilwxVYoXTN35YGSO883oeCyPXpUd1R6w3v4zR2Ux",
	"GOycxwGYTms9n1tc4w0T1NK60Ufv0GZaGKAVSTR2awYWzDXIypcwSBi3mCfOrtMcF4XbPLM187/faw9z",
	"MTWV5Yz+KUO92gzpxaeNT/fSd1f2GV2yNEtBZOmdvzsoSAQU6pxYDqhK6dIzlmG/13XGmNCMWzLsuXkv",
	"9QrKJyaKp/1JcN+4Despz9K+820yZ4s8j51/8gUxeqjkNID2MosiNCbJOFS4cGk8OGpOMe3+/fPM8lco",
	"DUb8QOP8ngJN3rlUYXss/dcClwojV3qxWLOdx853QA8NRmYrtavCP3FtsGyq8nl1QaAgcLHpuWQCtCa+",
	"fSPeFsnLV0VruQIKEWcobECNYVNXOsIx3Ig5o3m1+Y3Fv0EOR6jSuA1hUrvzafla45ShhgXjHKYoXOgR",
	"qIBw7KtNnSW81VvD0VGaKC131rmcafTbgfRhMTlyi/eZV3gT34OisT/IePUl88vDqn4bud5L8d6XN6Ee",
	"iarlKEfqx07t8g7MXzzl2p8/nvaRFAlnkYWggl04Bsrd6LJybVdm8i540O8/nlE/O4f4DhOXEaqScr82",
	"2iuZShyhqWbuO9LYbGazMF57duRosanRSeW8pn2PlMb51sOk1OSUzZLOzv8ZDRV5sG9WlVDe7hhMVUD5",
	"6v+WXeE4v1rgrMzwwWPaUHjEFZlEZiL+GsHssbIDp8ay3dh2/4S2lgh3K2DWQOYvFcNx0yzyBYHZfew6",
	"8lW0iX+h/aFo34Xrzph4gLWLq9USpf5CoUMV62wG/Em1de/etXlQr+Bi9v/BJfuDVu0OoGlv+Y/GZP3f",
	"AAAA//+bqejvrh4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
